spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    include-stacktrace: never

jwt:
  secret: 2zQoVpH4avwj6vD0hUvnpMtgnGFTz8xxcKBiL14cnaY=
  expiration: 900000